server:
  port: 3344

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/haimianbabe/springcloud-config.git
          search-paths:
            - springcloud-config
#          username: 1546413670@qq.com
#          password: wyp15897889746
          default-label: master
          skip-ssl-validation: true
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"